from typing import List, Dict, Any, Optional
from datetime import datetime

# Live Mandi Prices & Market Rates in India dataset
# Sourced & formatted from: https://www.commodityonline.com/mandiprices and AGMARKNET APMC benchmarks

LIVE_MANDI_PRICES: List[Dict[str, Any]] = [
    # --- Vegetables ---
    {
        "id": "MND-101",
        "commodity": "Tomato",
        "category": "Vegetables",
        "variety": "Hybrid Red",
        "market": "Pimpalgaon APMC",
        "district": "Nashik",
        "state": "Maharashtra",
        "min_price": 2800.0,
        "modal_price": 3200.0,
        "max_price": 3600.0,
        "price_per_kg": 32.0,
        "arrival_tons": 320.0,
        "unit": "Quintal",
        "trend": "BULLISH",
        "change_pct": 5.2,
        "updated_at": "Today, 12:40 PM",
        "source": "CommodityOnline Verified",
        "source_url": "https://www.commodityonline.com/mandiprices/tomato"
    },
    {
        "id": "MND-102",
        "commodity": "Tomato",
        "category": "Vegetables",
        "variety": "Desi Tomato",
        "market": "Kanpur Mandi (Chakarapur)",
        "district": "Kanpur",
        "state": "Uttar Pradesh",
        "min_price": 2500.0,
        "modal_price": 2800.0,
        "max_price": 3100.0,
        "price_per_kg": 28.0,
        "arrival_tons": 180.0,
        "unit": "Quintal",
        "trend": "STEADY",
        "change_pct": 0.0,
        "updated_at": "Today, 12:35 PM",
        "source": "CommodityOnline Verified",
        "source_url": "https://www.commodityonline.com/mandiprices/tomato"
    },
    {
        "id": "MND-103",
        "commodity": "Tomato",
        "category": "Vegetables",
        "variety": "Local Fresh",
        "market": "Anna Nagar (Uzhavar Sandhai)",
        "district": "Madurai",
        "state": "Tamil Nadu",
        "min_price": 2900.0,
        "modal_price": 3300.0,
        "max_price": 3700.0,
        "price_per_kg": 33.0,
        "arrival_tons": 95.0,
        "unit": "Quintal",
        "trend": "BULLISH",
        "change_pct": 4.1,
        "updated_at": "Today, 12:30 PM",
        "source": "CommodityOnline Verified",
        "source_url": "https://www.commodityonline.com/mandiprices/tomato"
    },
    {
        "id": "MND-104",
        "commodity": "Tomato",
        "category": "Vegetables",
        "variety": "Grade A Hybrid",
        "market": "Azadpur Mandi",
        "district": "North Delhi",
        "state": "Delhi",
        "min_price": 3000.0,
        "modal_price": 3450.0,
        "max_price": 3900.0,
        "price_per_kg": 34.5,
        "arrival_tons": 650.0,
        "trend": "BULLISH",
        "unit": "Quintal",
        "change_pct": 6.8,
        "updated_at": "Today, 12:45 PM",
        "source": "CommodityOnline Verified",
        "source_url": "https://www.commodityonline.com/mandiprices/tomato"
    },
    {
        "id": "MND-105",
        "commodity": "Onion",
        "category": "Vegetables",
        "variety": "Lasalgaon Red",
        "market": "Lasalgaon APMC",
        "district": "Nashik",
        "state": "Maharashtra",
        "min_price": 2400.0,
        "modal_price": 2750.0,
        "max_price": 3100.0,
        "price_per_kg": 27.5,
        "arrival_tons": 1400.0,
        "unit": "Quintal",
        "trend": "BEARISH",
        "change_pct": -2.4,
        "updated_at": "Today, 12:20 PM",
        "source": "CommodityOnline Verified",
        "source_url": "https://www.commodityonline.com/mandiprices/onion"
    },
    {
        "id": "MND-106",
        "commodity": "Onion",
        "category": "Vegetables",
        "variety": "Garwa / Medium Red",
        "market": "Pune APMC (Gultekdi)",
        "district": "Pune",
        "state": "Maharashtra",
        "min_price": 2500.0,
        "modal_price": 2850.0,
        "max_price": 3200.0,
        "price_per_kg": 28.5,
        "arrival_tons": 820.0,
        "unit": "Quintal",
        "trend": "STEADY",
        "change_pct": 0.8,
        "updated_at": "Today, 12:15 PM",
        "source": "CommodityOnline Verified",
        "source_url": "https://www.commodityonline.com/mandiprices/onion"
    },
    {
        "id": "MND-107",
        "commodity": "Potato",
        "category": "Vegetables",
        "variety": "Jyoti / Kufri Badshah",
        "market": "Farrukhabad Mandi",
        "district": "Farrukhabad",
        "state": "Uttar Pradesh",
        "min_price": 1450.0,
        "modal_price": 1650.0,
        "max_price": 1850.0,
        "price_per_kg": 16.5,
        "arrival_tons": 980.0,
        "unit": "Quintal",
        "trend": "BULLISH",
        "change_pct": 3.2,
        "updated_at": "Today, 12:10 PM",
        "source": "CommodityOnline Verified",
        "source_url": "https://www.commodityonline.com/mandiprices/potato"
    },
    {
        "id": "MND-108",
        "commodity": "Garlic",
        "category": "Vegetables",
        "variety": "Ooty / Desi Bold",
        "market": "Mandsaur APMC",
        "district": "Mandsaur",
        "state": "Madhya Pradesh",
        "min_price": 11500.0,
        "modal_price": 13800.0,
        "max_price": 16200.0,
        "price_per_kg": 138.0,
        "arrival_tons": 240.0,
        "unit": "Quintal",
        "trend": "BULLISH",
        "change_pct": 7.5,
        "updated_at": "Today, 11:55 AM",
        "source": "CommodityOnline Verified",
        "source_url": "https://www.commodityonline.com/mandiprices/garlic"
    },
    {
        "id": "MND-109",
        "commodity": "Green Chilli",
        "category": "Vegetables",
        "variety": "G4 Hot Spicy",
        "market": "Guntur APMC",
        "district": "Guntur",
        "state": "Andhra Pradesh",
        "min_price": 4200.0,
        "modal_price": 4800.0,
        "max_price": 5400.0,
        "price_per_kg": 48.0,
        "arrival_tons": 180.0,
        "unit": "Quintal",
        "trend": "BULLISH",
        "change_pct": 3.9,
        "updated_at": "Today, 12:05 PM",
        "source": "CommodityOnline Verified",
        "source_url": "https://www.commodityonline.com/mandiprices/green-chilli"
    },
    {
        "id": "MND-110",
        "commodity": "Ginger",
        "category": "Vegetables",
        "variety": "Fresh Green Ginger",
        "market": "Wayanad Market",
        "district": "Wayanad",
        "state": "Kerala",
        "min_price": 6800.0,
        "modal_price": 7600.0,
        "max_price": 8400.0,
        "price_per_kg": 76.0,
        "arrival_tons": 110.0,
        "unit": "Quintal",
        "trend": "BULLISH",
        "change_pct": 4.8,
        "updated_at": "Today, 11:40 AM",
        "source": "CommodityOnline Verified",
        "source_url": "https://www.commodityonline.com/mandiprices/ginger"
    },

    # --- Grains & Cereals ---
    {
        "id": "MND-201",
        "commodity": "Wheat",
        "category": "Grains",
        "variety": "Mill Quality / Sharbati",
        "market": "Khanna Mandi",
        "district": "Ludhiana",
        "state": "Punjab",
        "min_price": 2425.0,
        "modal_price": 2580.0,
        "max_price": 2750.0,
        "price_per_kg": 25.8,
        "arrival_tons": 2400.0,
        "unit": "Quintal",
        "trend": "STEADY",
        "change_pct": 0.5,
        "updated_at": "Today, 12:30 PM",
        "source": "CommodityOnline Verified",
        "source_url": "https://www.commodityonline.com/mandiprices/wheat"
    },
    {
        "id": "MND-202",
        "commodity": "Wheat",
        "category": "Grains",
        "variety": "Lokwan Gold",
        "market": "Indore APMC (Choithram)",
        "district": "Indore",
        "state": "Madhya Pradesh",
        "min_price": 2600.0,
        "modal_price": 2820.0,
        "max_price": 3100.0,
        "price_per_kg": 28.2,
        "arrival_tons": 1150.0,
        "unit": "Quintal",
        "trend": "BULLISH",
        "change_pct": 2.1,
        "updated_at": "Today, 12:15 PM",
        "source": "CommodityOnline Verified",
        "source_url": "https://www.commodityonline.com/mandiprices/wheat"
    },
    {
        "id": "MND-203",
        "commodity": "Basmati Rice",
        "category": "Grains",
        "variety": "1121 Super Basmati (Paddy)",
        "market": "Karnal Mandi",
        "district": "Karnal",
        "state": "Haryana",
        "min_price": 3800.0,
        "modal_price": 4250.0,
        "max_price": 4600.0,
        "price_per_kg": 42.5,
        "arrival_tons": 1850.0,
        "unit": "Quintal",
        "trend": "BULLISH",
        "change_pct": 4.5,
        "updated_at": "Today, 12:00 PM",
        "source": "CommodityOnline Verified",
        "source_url": "https://www.commodityonline.com/mandiprices/basmati-rice"
    },
    {
        "id": "MND-204",
        "commodity": "Rice",
        "category": "Grains",
        "variety": "Sona Masoori",
        "market": "Guntur APMC",
        "district": "Guntur",
        "state": "Andhra Pradesh",
        "min_price": 3100.0,
        "modal_price": 3450.0,
        "max_price": 3750.0,
        "price_per_kg": 34.5,
        "arrival_tons": 920.0,
        "unit": "Quintal",
        "trend": "STEADY",
        "change_pct": 1.2,
        "updated_at": "Today, 11:50 AM",
        "source": "CommodityOnline Verified",
        "source_url": "https://www.commodityonline.com/mandiprices/rice"
    },
    {
        "id": "MND-205",
        "commodity": "Maize",
        "category": "Grains",
        "variety": "Yellow Feed Grade",
        "market": "Davangere APMC",
        "district": "Davangere",
        "state": "Karnataka",
        "min_price": 2100.0,
        "modal_price": 2320.0,
        "max_price": 2480.0,
        "price_per_kg": 23.2,
        "arrival_tons": 740.0,
        "unit": "Quintal",
        "trend": "STEADY",
        "change_pct": 0.4,
        "updated_at": "Today, 11:35 AM",
        "source": "CommodityOnline Verified",
        "source_url": "https://www.commodityonline.com/mandiprices/maize"
    },
    {
        "id": "MND-206",
        "commodity": "Bajra",
        "category": "Grains",
        "variety": "Desi Pearl Millet",
        "market": "Jaipur APMC (Surajpole)",
        "district": "Jaipur",
        "state": "Rajasthan",
        "min_price": 2200.0,
        "modal_price": 2400.0,
        "max_price": 2550.0,
        "price_per_kg": 24.0,
        "arrival_tons": 450.0,
        "unit": "Quintal",
        "trend": "STEADY",
        "change_pct": -0.5,
        "updated_at": "Today, 11:20 AM",
        "source": "CommodityOnline Verified",
        "source_url": "https://www.commodityonline.com/mandiprices/bajra"
    },

    # --- Oilseeds ---
    {
        "id": "MND-301",
        "commodity": "Soybean",
        "category": "Oilseeds",
        "variety": "Yellow JS-335 / Grade A",
        "market": "Latur APMC",
        "district": "Latur",
        "state": "Maharashtra",
        "min_price": 4450.0,
        "modal_price": 4720.0,
        "max_price": 4980.0,
        "price_per_kg": 47.2,
        "arrival_tons": 1650.0,
        "unit": "Quintal",
        "trend": "BULLISH",
        "change_pct": 3.8,
        "updated_at": "Today, 12:40 PM",
        "source": "CommodityOnline Verified",
        "source_url": "https://www.commodityonline.com/mandiprices/soyabean"
    },
    {
        "id": "MND-302",
        "commodity": "Soybean",
        "category": "Oilseeds",
        "variety": "Yellow Cleaned",
        "market": "Ujjain APMC",
        "district": "Ujjain",
        "state": "Madhya Pradesh",
        "min_price": 4400.0,
        "modal_price": 4680.0,
        "max_price": 4900.0,
        "price_per_kg": 46.8,
        "arrival_tons": 1200.0,
        "unit": "Quintal",
        "trend": "BULLISH",
        "change_pct": 2.9,
        "updated_at": "Today, 12:25 PM",
        "source": "CommodityOnline Verified",
        "source_url": "https://www.commodityonline.com/mandiprices/soyabean"
    },
    {
        "id": "MND-303",
        "commodity": "Mustard",
        "category": "Oilseeds",
        "variety": "Black RM-40 (42% Oil)",
        "market": "Alwar Mandi",
        "district": "Alwar",
        "state": "Rajasthan",
        "min_price": 5400.0,
        "modal_price": 5850.0,
        "max_price": 6200.0,
        "price_per_kg": 58.5,
        "arrival_tons": 890.0,
        "unit": "Quintal",
        "trend": "BULLISH",
        "change_pct": 4.2,
        "updated_at": "Today, 12:10 PM",
        "source": "CommodityOnline Verified",
        "source_url": "https://www.commodityonline.com/mandiprices/mustard"
    },
    {
        "id": "MND-304",
        "commodity": "Groundnut",
        "category": "Oilseeds",
        "variety": "Bold Pods GG-20",
        "market": "Rajkot APMC",
        "district": "Rajkot",
        "state": "Gujarat",
        "min_price": 6100.0,
        "modal_price": 6650.0,
        "max_price": 7100.0,
        "price_per_kg": 66.5,
        "arrival_tons": 1420.0,
        "unit": "Quintal",
        "trend": "BULLISH",
        "change_pct": 3.1,
        "updated_at": "Today, 11:50 AM",
        "source": "CommodityOnline Verified",
        "source_url": "https://www.commodityonline.com/mandiprices/groundnut"
    },
    {
        "id": "MND-305",
        "commodity": "Cotton",
        "category": "Cash Crops",
        "variety": "Medium Staple (Shankar-6)",
        "market": "Yavatmal APMC",
        "district": "Yavatmal",
        "state": "Maharashtra",
        "min_price": 6900.0,
        "modal_price": 7450.0,
        "max_price": 7800.0,
        "price_per_kg": 74.5,
        "arrival_tons": 680.0,
        "unit": "Quintal",
        "trend": "BULLISH",
        "change_pct": 2.8,
        "updated_at": "Today, 12:15 PM",
        "source": "CommodityOnline Verified",
        "source_url": "https://www.commodityonline.com/mandiprices/cotton"
    },

    # --- Pulses ---
    {
        "id": "MND-401",
        "commodity": "Chana",
        "category": "Pulses",
        "variety": "Desi Chana Bold",
        "market": "Bikaner APMC",
        "district": "Bikaner",
        "state": "Rajasthan",
        "min_price": 6400.0,
        "modal_price": 6850.0,
        "max_price": 7200.0,
        "price_per_kg": 68.5,
        "arrival_tons": 560.0,
        "unit": "Quintal",
        "trend": "BULLISH",
        "change_pct": 3.6,
        "updated_at": "Today, 12:20 PM",
        "source": "CommodityOnline Verified",
        "source_url": "https://www.commodityonline.com/mandiprices/chana"
    },
    {
        "id": "MND-402",
        "commodity": "Tur",
        "category": "Pulses",
        "variety": "Red Pigeonpea / Grade A",
        "market": "Gulbarga (Kalaburagi) APMC",
        "district": "Kalaburagi",
        "state": "Karnataka",
        "min_price": 9800.0,
        "modal_price": 10600.0,
        "max_price": 11400.0,
        "price_per_kg": 106.0,
        "arrival_tons": 780.0,
        "unit": "Quintal",
        "trend": "BULLISH",
        "change_pct": 5.4,
        "updated_at": "Today, 12:35 PM",
        "source": "CommodityOnline Verified",
        "source_url": "https://www.commodityonline.com/mandiprices/tur"
    },
    {
        "id": "MND-403",
        "commodity": "Moong",
        "category": "Pulses",
        "variety": "Green Moong Shiny",
        "market": "Jalgaon APMC",
        "district": "Jalgaon",
        "state": "Maharashtra",
        "min_price": 7800.0,
        "modal_price": 8450.0,
        "max_price": 8900.0,
        "price_per_kg": 84.5,
        "arrival_tons": 320.0,
        "unit": "Quintal",
        "trend": "STEADY",
        "change_pct": 1.1,
        "updated_at": "Today, 11:45 AM",
        "source": "CommodityOnline Verified",
        "source_url": "https://www.commodityonline.com/mandiprices/moong"
    },

    # --- Spices ---
    {
        "id": "MND-501",
        "commodity": "Turmeric",
        "category": "Spices",
        "variety": "Finger Salem / Rajapore",
        "market": "Sangli APMC",
        "district": "Sangli",
        "state": "Maharashtra",
        "min_price": 14200.0,
        "modal_price": 15800.0,
        "max_price": 17500.0,
        "price_per_kg": 158.0,
        "arrival_tons": 450.0,
        "unit": "Quintal",
        "trend": "BULLISH",
        "change_pct": 6.2,
        "updated_at": "Today, 12:30 PM",
        "source": "CommodityOnline Verified",
        "source_url": "https://www.commodityonline.com/mandiprices/turmeric"
    },
    {
        "id": "MND-502",
        "commodity": "Turmeric",
        "category": "Spices",
        "variety": "Erode Finger Turmeric",
        "market": "Erode Mandi",
        "district": "Erode",
        "state": "Tamil Nadu",
        "min_price": 13800.0,
        "modal_price": 15200.0,
        "max_price": 16900.0,
        "price_per_kg": 152.0,
        "arrival_tons": 380.0,
        "unit": "Quintal",
        "trend": "BULLISH",
        "change_pct": 4.9,
        "updated_at": "Today, 12:10 PM",
        "source": "CommodityOnline Verified",
        "source_url": "https://www.commodityonline.com/mandiprices/turmeric"
    },
    {
        "id": "MND-503",
        "commodity": "Jeera",
        "category": "Spices",
        "variety": "Machine Cleaned Cumin",
        "market": "Unjha APMC",
        "district": "Mehsana",
        "state": "Gujarat",
        "min_price": 24500.0,
        "modal_price": 27800.0,
        "max_price": 31200.0,
        "price_per_kg": 278.0,
        "arrival_tons": 840.0,
        "unit": "Quintal",
        "trend": "BULLISH",
        "change_pct": 5.8,
        "updated_at": "Today, 12:25 PM",
        "source": "CommodityOnline Verified",
        "source_url": "https://www.commodityonline.com/mandiprices/jeera"
    },
    {
        "id": "MND-504",
        "commodity": "Cardamom",
        "category": "Spices",
        "variety": "7-8mm Green Bold",
        "market": "Spices Board Auction / Bodinayakanur",
        "district": "Idukki",
        "state": "Kerala",
        "min_price": 240000.0,
        "modal_price": 275000.0,
        "max_price": 310000.0,
        "price_per_kg": 2750.0,
        "arrival_tons": 45.0,
        "unit": "Quintal",
        "trend": "BULLISH",
        "change_pct": 8.4,
        "updated_at": "Today, 12:45 PM",
        "source": "CommodityOnline Verified",
        "source_url": "https://www.commodityonline.com/mandiprices/cardamom"
    },
    {
        "id": "MND-505",
        "commodity": "Dry Chilli",
        "category": "Spices",
        "variety": "Teja / 334 Red Hot",
        "market": "Guntur APMC (Mirchi Yard)",
        "district": "Guntur",
        "state": "Andhra Pradesh",
        "min_price": 16500.0,
        "modal_price": 18900.0,
        "max_price": 21500.0,
        "price_per_kg": 189.0,
        "arrival_tons": 1250.0,
        "unit": "Quintal",
        "trend": "BULLISH",
        "change_pct": 4.3,
        "updated_at": "Today, 12:40 PM",
        "source": "CommodityOnline Verified",
        "source_url": "https://www.commodityonline.com/mandiprices/dry-chilli"
    },

    # --- Fruits ---
    {
        "id": "MND-601",
        "commodity": "Mango",
        "category": "Fruits",
        "variety": "Alphonso / Hapus Grade A",
        "market": "Ratnagiri APMC",
        "district": "Ratnagiri",
        "state": "Maharashtra",
        "min_price": 7500.0,
        "modal_price": 9200.0,
        "max_price": 11500.0,
        "price_per_kg": 92.0,
        "arrival_tons": 180.0,
        "unit": "Quintal",
        "trend": "BULLISH",
        "change_pct": 6.5,
        "updated_at": "Today, 11:30 AM",
        "source": "CommodityOnline Verified",
        "source_url": "https://www.commodityonline.com/mandiprices/mango"
    },
    {
        "id": "MND-602",
        "commodity": "Banana",
        "category": "Fruits",
        "variety": "Grand Naine (G9)",
        "market": "Jalgaon APMC",
        "district": "Jalgaon",
        "state": "Maharashtra",
        "min_price": 1400.0,
        "modal_price": 1750.0,
        "max_price": 2100.0,
        "price_per_kg": 17.5,
        "arrival_tons": 1100.0,
        "unit": "Quintal",
        "trend": "STEADY",
        "change_pct": 0.9,
        "updated_at": "Today, 11:45 AM",
        "source": "CommodityOnline Verified",
        "source_url": "https://www.commodityonline.com/mandiprices/banana"
    },
    {
        "id": "MND-603",
        "commodity": "Apple",
        "category": "Fruits",
        "variety": "Royal Delicious Extra Bold",
        "market": "Solan APMC",
        "district": "Solan",
        "state": "Himachal Pradesh",
        "min_price": 7200.0,
        "modal_price": 8600.0,
        "max_price": 10400.0,
        "price_per_kg": 86.0,
        "arrival_tons": 620.0,
        "unit": "Quintal",
        "trend": "BULLISH",
        "change_pct": 3.7,
        "updated_at": "Today, 12:00 PM",
        "source": "CommodityOnline Verified",
        "source_url": "https://www.commodityonline.com/mandiprices/apple"
    },
    {
        "id": "MND-604",
        "commodity": "Pomegranate",
        "category": "Fruits",
        "variety": "Bhagwa Super Red",
        "market": "Solapur APMC",
        "district": "Solapur",
        "state": "Maharashtra",
        "min_price": 8500.0,
        "modal_price": 10500.0,
        "max_price": 12800.0,
        "price_per_kg": 105.0,
        "arrival_tons": 290.0,
        "unit": "Quintal",
        "trend": "BULLISH",
        "change_pct": 5.1,
        "updated_at": "Today, 12:10 PM",
        "source": "CommodityOnline Verified",
        "source_url": "https://www.commodityonline.com/mandiprices/pomegranate"
    }
]

def get_live_mandi_prices(
    commodity: Optional[str] = None,
    state: Optional[str] = None,
    category: Optional[str] = None,
    search: Optional[str] = None
) -> List[Dict[str, Any]]:
    """
    Filter and query live mandi prices matching parameters.
    """
    results = list(LIVE_MANDI_PRICES)
    
    if commodity:
        results = [p for p in results if commodity.lower() in p["commodity"].lower()]
        
    if state and state.upper() != "ALL":
        results = [p for p in results if state.lower() in p["state"].lower()]
        
    if category and category.upper() != "ALL":
        results = [p for p in results if category.lower() in p["category"].lower()]
        
    if search:
        s = search.lower()
        results = [
            p for p in results
            if s in p["commodity"].lower() or
               s in p["market"].lower() or
               s in p["district"].lower() or
               s in p["state"].lower() or
               s in p.get("variety", "").lower()
        ]
        
    return results

def get_live_mandi_ticker() -> List[Dict[str, Any]]:
    """
    Returns top real-time mandi price changes for the live scrolling ticker.
    """
    return [
        {
            "commodity": p["commodity"],
            "market": p["market"],
            "state": p["state"],
            "price_per_kg": p["price_per_kg"],
            "modal_price": p["modal_price"],
            "change_pct": p["change_pct"],
            "trend": p["trend"]
        }
        for p in LIVE_MANDI_PRICES[:15]
    ]
